### PR TITLE
reported load balance fix

### PR DESCRIPTION
**Pull request by carrardt**
To be tested against regular bulks and with more heterogeneous particle systems.
should produce better shaped domain partitions, and limit ghost exchange when two different possible cuts have similar compute costs.

recommend thorough testing on supercomputers before merge

### CODE REVIEW

**Comment by lafourcadep** [comment]
J'ai testé sur plusieurs configurations il semble que les modifs vont dans le bon sens -> une boîte cubique sur 8 MPI est bien découpée en 8 cubes et non 8 plaques

**Comment by lafourcadep** [comment]
@carrardt waiting for parallel-execution-streaming pull request is done. When it's done, we'll merge main into rcb_load_balance_fixup for thorough testing on supercomputers before final merge as requested.

**Comment by rprat-pro** [comment]
> @carrardt waiting for parallel-execution-streaming pull request is done. When it's done, we'll merge main into rcb_load_balance_fixup for thorough testing on supercomputers before final merge as requested.

pls re-check it.

**Review by lafourcadep — APPROVED** [review]
Merge main into rcb_load_balance_fixup prior to validate pull request. 
Tests are ok on both laptop and supercomputer for in-place rcb.

**Pull request merged**
